config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  get 'books/booksearch', to: 'books#new'
  root 'books#index'
  resources :books do
    resources :likes, only: [:create, :destroy]
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_books, through: :likes, source: :book
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 


  def already_liked?(book)
    self.likes.exists?(book_id: book.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    if params[:search] == nil
      @books = Book.all.order("created_at DESC").page(params[:page]).per(5)
    elsif params[:search] == ""
      @books= Book.all.page(params[:page]).per(5) 
    else
      @search = params[:search]
      @books = Book.where("title LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(5)
    end
    @rank_books = Book.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}.first(5)
    end

  def new
     @book = Book.new

     if params[:keyword].present?
      require 'net/http'
      url = 'https://www.googleapis.com/books/v1/volumes?q='
      request = url + params[:keyword]
      enc_str = URI.encode(request)
      uri = URI.parse(enc_str)
      json = Net::HTTP.get(uri)
      @bookjson = JSON.parse(json)

      count = 5 #検索結果に表示する数
      @books = Array.new(count).map{Array.new(4)}
      count.times do |x|
        @books[x][0] = @bookjson.dig("items", x, "volumeInfo", "title")
        @books[x][1] = @bookjson.dig("items", x, "volumeInfo", "imageLinks", "thumbnail")
        @books[x][2] = @bookjson.dig("items", x, "volumeInfo", "authors")
        @books[x][2] = @books[x][2].join(',') if @books[x][2] #複数著者をカンマで区切る
        @books[x][3] = @bookjson.dig("items", x, "volumeInfo", "industryIdentifiers", 0, "identifier")
      end
    end
  
    @title = params[:title] if params[:title].present?
    @author = params[:author] if params[:author].present?
    @img = params[:img] if params[:img].present?
  end


  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    if book.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    if params[:keyword].present?
      require 'net/http'
      url = 'https://www.googleapis.com/books/v1/volumes?q='
      request = url + params[:keyword]
      enc_str = URI.encode(request)
      uri = URI.parse(enc_str)
      json = Net::HTTP.get(uri)
      @bookjson = JSON.parse(json)

      count = 5 #検索結果に表示する数
      @books = Array.new(count).map{Array.new(4)}
      count.times do |x|
        @books[x][0] = @bookjson.dig("items", x, "volumeInfo", "title")
        @books[x][1] = @bookjson.dig("items", x, "volumeInfo", "imageLinks", "thumbnail")
        @books[x][2] = @bookjson.dig("items", x, "volumeInfo", "authors")
        @books[x][2] = @books[x][2].join(',') if @books[x][2] #複数著者をカンマで区切る
        @books[x][3] = @bookjson.dig("items", x, "volumeInfo", "industryIdentifiers", 0, "identifier")
      end
    end
    @title = params[:title] if params[:title].present?
    @author = params[:author] if params[:author].present?
    @img = params[:image] if params[:image].present?
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to :action => "show", :id => book.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to action: :index
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :learn, :about, :category, :overrall, :image)
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(book_id: params[:book_id]) 
    redirect_back(fallback_location: books_path)
  end

  def destroy
    like = Like.find_by(book_id: params[:book_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: books_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def getPercent(number) 
    if number.present?
      calPercent = number/5.to_f * 100
      percent = calPercent.round
      return percent.to_s
    else
      return 0
    end
  end
 
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>
  <br>
  <br>
  <br>
  <div class="post-container">
  <br>
  <br>
  <h2>本の編集</h2>
  <br>
  <br>
  <%= form_for @book do |f| %>
    <div class="field">
      <h3>
        <%= f.label :本のタイトル %>
        <%= f.text_field :title, class: 'form-control', :size => 30 %>
      </h3>
    </div>
    <br>
    <div class="field">
      <h3>
        <%= f.label :著者 %>
        <%= f.text_field :author, class: 'form-control', :size => 30 %>      
       </h3>
    </div>
    <br>
    <br>
    <div class="field">
      <h3>
        <%= f.label :本のカテゴリー %>
        <%= f.select :category, 
        [["自己啓発", "自己啓発"], 
        ["文学・評論", "文学・評論"],
        ["ビジネス・経済","ビジネス・経済"],
        ["歴史・地理", "歴史・地理"] ,
        ["政治・社会", "政治・社会"],
        ["芸能・エンターテイメント", "芸能・エンターテイメント"],
        ["アート・建築・デザイン", "アート・建築・デザイン"],
        ["人文・思想・宗教", "人文・思想・宗教"],
        ["暮らし・健康・料理", "暮らし・健康・料理"],
        ["サイエンス・テクノロジー", "サイエンス・テクノロジー"],
        ["趣味・実用", "趣味・実用"],
        ["旅行・紀行", "旅行・紀行"],
        ["学習参考書", "学習参考書"],
        ["コミックス", "コミックス"],
        ["その他", "その他"]], include_blank: "選択して下さい" %>
      </h3>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div class="field">
      <h3>
        <%= f.label :どんな本？（一言で！） %>
        <%= f.text_field :learn,class: 'form-control', size: 140 %>
    </h3>
    </div>
    <br>

    <div class="field">
      <h3>
        <%= f.label :この本から学んだこと %><br>
        <%= f.text_area :about,class: 'form-control', size: "80x6" %>
      </h3>
    </div>
    <br>
    <h3>総合評価</h3>
    <br>
   <div class= "star-rating">
     <div class="post_form">
       <%= f.radio_button :overrall, 5 ,id: 'star1'%>
       <label for="star1"><span class="text">感動した</span>★</label>

       <%= f.radio_button :overrall, 4 ,id: 'star2'%>
       <label for="star2"><span class="text">イイネ！</span>★</label>

       <%= f.radio_button :overrall, 3 ,id: 'star3'%>
       <label for="star3"><span class="text">まあまあ</span>★</label>

       <%= f.radio_button :overrall, 2 ,id: 'star4'%>
       <label for="star4"><span class="text">うーん。</span>★</label>

       <%= f.radio_button :overrall, 1 ,id: 'star5'%>
       <label for="star5"><span class="text">最悪</span>★</label>
     </div>
  </div>
  <br>

  <%= f.submit "本を再投稿する" %>
<% end %>
<br>
<br>

  <h3>
    <%= link_to "本の一覧に戻る", books_path %>
  </h3>
  <br>
  <br>
</div>

app/views/books/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
    <section id="first-block">
      <p class="firstblock-name">
      <br>
      <br>
        <div class= "searchbox">
         <h3>BOOK SHARE</h3>
         <h3>〜本と過ごす日〜</h3>
         <br>
         <br>
          <h3>投稿を検索</h3>
            <%= form_tag({controller:"books",action:"index"}, method: :get) do %>
            <%= text_field_tag :search %>
            <%= submit_tag '検索する' %>
            <% end %>
          <% if user_signed_in? %>
          <h3>
            <%= link_to "マイページ", user_path(current_user.id), class: "btn-flat-border" %>
            <%= link_to "新規投稿", new_book_path, class: "btn-flat-border" %>
          </h3>
          <% end %>
        </div>
      <br>

    </section>
    <section id="second-block">

    <h1>What's BOOK SHARE?<h1>
     <div class="aboutbookshare">
       <div class="about-item">
         <br>
         <div class="circle"></div>
         <div class="circle"></div>
       </div>
       <div class="about-item">
        <h3>〜読書した本をアウトプットできるサイト〜</h3>
          <h3>
            <p>・どんな本なのか<br>
            <p>・その本から得られたことは何なのか<br>
            <p>・読んで面白かったのか<br>
            <br>
            について記録することが出来ます。</h3>
            <br>
       </div>
       <div class="about-item">
         <br>
         <div class="circle"></div>
         <div class="circle"></div>
        </div>
      </div>
    </section>
  
    <section id="third-block">
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1>BOOK SHARE RANKING👑</h1>
    <br>
      <div class="rankingrate">
        <h1>No.1</h1>
        <h1>No.2</h1>
        <h1>No.3</h1>
        <h1>No.4</h1>
        <h1>No.5</h1>
      </div>
    <div class="books-container">
     
      <% @rank_books.each do |t| %>
      <div class="blockwrapper">
        <div class=block>
          <h3>
            <p class= "blockthumb">
            <%= image_tag t.image, size: "100x220" if t.image? %>
          <br>
          <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to book_like_path(id: t.id, book_id: t.id), method: :delete do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to book_likes_path(id: t.id, book_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
          <% @rank_books.each do |t| %>
        <% end %>
        <%= link_to "詳細", book_path(t.id) %> 
        </h3>
        </p>
        <div class="bottomcontainer">
        <a href="/users/<%= t.user.id %>">
        <%= t.user.name %></a>
        <%= t.created_at.to_s(:datetime_jp) %>
          <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(t.overrall) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
          </span> 
        </div>
      </div>
    </div>
    <br>
     <% end %>
    
    <br>
    <br>
    <br>
    <br>
    </section>
    <br>
    <h3>
    <%= paginate @books %>
    <br>
    <br>
    <section id="forth-block">
      <h1>New Post</h1>
      <div class="books-container">
        <% @books.each do |t| %>
        <div class="blockwrapper">
          <div class=mypostblock>
            <h3>
              <p class= "blockthumb">
              <%= image_tag t.image, size: "100x220" if t.image? %>
              <br>
              <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                  <%= link_to book_like_path(id: t.id, book_id: t.id), method: :delete do %>
                    <i class="far fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% else %>
                  <%= link_to book_likes_path(id: t.id, book_id: t.id), method: :post do %>
                    <i class="far fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% end %>
            <% else %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
              <%= link_to "詳細", book_path(t.id) %>
            <% if user_signed_in? && current_user.id == t.user_id %>  
              <%= link_to "編集", edit_book_path(t.id) %>
              <%= link_to "削除", book_path(t.id), method: :delete %>
            <% end %>
            </p>
          </h3>
          <div class="bottomcontainer">
          <p>
            <a href="/users/<%= t.user.id %>">
            <%= t.user.name %></a>
            <%= t.created_at.to_s(:datetime_jp) %>
              <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.overrall) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span> 
          </p>
        </div>
      </div>
    </div>
    <br>
     <% end %>
  </div>
    <br>
    <br>
      <% if user_signed_in? %>
            <h3>
            <%= link_to "＋もっと見る", user_path(current_user.id), class:"btn-gradient-simple" %>
            </h3>
      <% end %>
      <br>
      <% if user_signed_in? %>
          <h3>
            <%= link_to "マイページ", user_path(current_user.id), class: "btn-flat-border" %>
            <%= link_to "新規投稿", new_book_path, class: "btn-flat-border" %>
          </h3>
          <% end %>
    </section>

app/views/books/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>
<br>
<br>
<br>
<div class="post-container">
  <h2>書籍の新規登録</h2>
  <%= form_tag('booksearch', method: :get) do %>
    <div class="input-group">
      <%= search_field_tag "keyword", params[:keyword], class: "form-control", placeholder: "キーワード検索" %>
        <span class="input-group-btn">
          <%= submit_tag "検索", class: "btn-btn-primary" %>
        </span>
    </div>
   <% end %>
  <h3>検索結果</h3>
  <% if @books.present? %>
    <% @books.each do |book| %>
       <img src="<%= book[1] %>" width="40" vspace="2">
       <%= link_to book[0], controller: "books", action: "new", title: book[0], author: book[2], img: book[1] %>
      <%= book[2] %> | 
    <% end %>
  <% end %>
  <br>
  <br>
  <h3>
    <%= form_with scope: :book, url: books_path, local: true do |form| %>
    <%= form.label :本のタイトル %>
    <%= form.text_field :title, class: 'form-control', value: "#{@title}" %>
    <%= form.label :著者 %>
    <%= form.text_field :author, class: 'form-control', value: "#{@author}" %>
  </h3>
    <%= form.hidden_field :image, class: 'form-control', value: "#{@img}" %>
    <br>
    <br>
    <h2>
      <button type="button" onclick="location.reload();">確定</button> 
    </h2>
    <h3>↑一度確定ボタンを押してください</h3>
    <br>
    <br>
  <div class="field">
    <h3>
      <%= form.label :category, "本のカテゴリー" %>
      <%= form.select :category, 
      [["自己啓発", "自己啓発"], 
      ["文学・評論", "文学・評論"],
      ["ビジネス・経済","ビジネス・経済"],
      ["歴史・地理", "歴史・地理"] ,
      ["政治・社会", "政治・社会"],
      ["芸能・エンターテイメント", "芸能・エンターテイメント"],
      ["アート・建築・デザイン", "アート・建築・デザイン"],
      ["人文・思想・宗教", "人文・思想・宗教"],
      ["暮らし・健康・料理", "暮らし・健康・料理"],
      ["サイエンス・テクノロジー", "サイエンス・テクノロジー"],
      ["趣味・実用", "趣味・実用"],
      ["旅行・紀行", "旅行・紀行"],
      ["学習参考書", "学習参考書"],
      ["コミックス", "コミックス"],
      ["その他", "その他"]], include_blank: "選択して下さい" %>
    </h3>
  </div>
  <br>
  <br>
  <br>
  <div class="field">
  <h3>
    <%= form.label :どんな本？（一言で！） %>
    <%= form.text_field :learn,size: 140 %>
  </h3>
  </div>
  <br>
  <div class="field">
  <h3>
    <%= form.label :この本から学んだこと %><br>
    <%= form.text_area :about,class: "hoge", size: "140x6" %>
  </h3>
  </div>
  <br>
  <h3>総合評価</h3>
  <br>
  <div class= "star-rating">
   <div class="post_form">
    <%= form.radio_button :overrall, 5 ,id: 'star1'%>
    <label for="star1"><span class="text">感動した</span>★</label>

    <%= form.radio_button :overrall, 4 ,id: 'star2'%>
    <label for="star2"><span class="text">イイネ！</span>★</label>

    <%= form.radio_button :overrall, 3 ,id: 'star3'%>
    <label for="star3"><span class="text">まあまあ</span>★</label>

    <%= form.radio_button :overrall, 2 ,id: 'star4'%>
    <label for="star4"><span class="text">うーん。</span>★</label>

    <%= form.radio_button :overrall, 1 ,id: 'star5'%>
    <label for="star5"><span class="text">最悪。</span>★</label>
    </div>
  </div>
    <br>
    <br>
    <br>
    <div class= "evaluation">
      <h3>
       <p class="starevaliation">
       ★・・・最悪だった。読まなくていいと思う。<br>
       ★★・・・うーん。いまいちかな。そんなにオススメはしない。<br>
       ★★★・・・まあまあ良かった。気になったら読んでみて〜<br>
       ★★★★・・・イイネ！出来れば読んでほしいな〜<br>
       ★★★★★・・・感動した、、！ぜひ読んで欲しい！！！<br>
      </h3>
      </p>
      <br>
    </div>
   <%= form.submit "本を投稿する" %>
   <% end %>
  <h3>
    <%= link_to "本の一覧に戻る", books_path %>
  </h3>
  <br>

  

app/views/books/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

<section id= "edit-block">
   <div class="imageblock">
      <%= image_tag @book.image, size: "320x400" if @book.image? %>
      <br>
      <h3>いいねしたユーザー
         <% @book.liked_users.each do |user| %>
        <li>
          <%= user.name %>
        </li>
      <% end %>
      <br>
      <br>
      <a href="https://www.amazon.co.jp/%E6%9C%AC-%E6%9B%B8%E7%B1%8D-%E9%80%9A%E8%B2%A9/b/?ie=UTF8&node=465392&ref_=nav_cs_books_990d615e94b14c8da5e8ca284e4adc9e" class="btn-gradient-3d-simple">Amazonで見てみる👀</a>

      <br>
      <br>
      <%= link_to "本の一覧に戻る", books_path, class: "btn-gradient-3d-orange" %>
      </h3>
    </div>

  <div class="form-wrapper">
    <div class="field">
      <br>
      <h3>【本の詳細情報】</h3>
      <div class="showblock">
            <h3>本のタイトル：<%= @book.title %></h3>
            <h3>本の著者：<%= @book.author %></h3>
            <h3>本のカテゴリー：<%= @book.category %></h3>
            <h3>その本を一言でまとめると：<%= @book.learn%></h3>
            <h3>その本で学んだこと：<%= simple_format(@book.about) %></h3>
            <h3><%= @book.created_at.to_s(:datetime_jp) %></h3>
      </div>
    </div>
  </div>
  <h3>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@book) %>
          <%= link_to book_like_path(@book), method: :delete do %>
          <i class="fas fa-heart"></i><%= @book.likes.count %>
          <% end %>
      <% else %>
            <%= link_to book_likes_path(@book), method: :post do %>
            <i class="far fa-heart"></i><%= @book.likes.count %>
            <% end %>
      <% end %>
  <% else %>
        <i class="far fa-heart"></i><%= @book.likes.count %>
  <% end %>
  </h3>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOK SHARE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Yomogi&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Patua+One&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
  </head>

  <body>
   <header>
      <h1>
        <a href="/">BOOK SHARE</a>
      </h1>
      
      <div class="header-list">
        <ul class="gnavi">
          <li><%= link_to "ホーム", books_path %></li>
          <li><%= link_to "新規投稿",new_book_path %></li>
          <li>
             <% if user_signed_in? %>
             <%= link_to "マイページ", user_path(current_user.id) %>
             <% end %>
          </li>
        </ul>
          <% if user_signed_in? %>
            <li><%= button_to 'ログアウト', destroy_user_session_path, method:  :delete %></li>
          <% else %>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </div>
  </header>
    <main>
      <%= yield %>
    </main>
    <footer>
     <p>Copyright @ BOOK SHARE All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name), class: "share_text" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか？", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<br>
<br>
<h3>ーマイページー</h3>
<h3>
  <br>
  <p>名前 : <%= @user.name %></p>
  <p>メールアドレス : <%= @user.email %></p>
  <p>プロフィール : <%= @user.profile %></p>

  <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path, class:"btn-gradient-3d-simple" %>
  <% end %>
</h3>
<br>
<br>
<h3>ーユーザーの投稿一覧ー</h3>
<br>
<% @user.books.each do |t| %>
<div class="blockwrapper">
        <div class=block>
         <h3>
          <p class= "blockthumb">
            <%= image_tag t.image, size: "100x300" if t.image? %>
          </p>
           <div class="bottomcontainer">
              <h3>
              <%= t.title %>
              <br>
              <%= link_to "詳細", book_path(t.id), class:"btn-gradient-3d-orange" %>
              <%= link_to "編集", edit_book_path(t.id), class:"btn-gradient-3d-simple" %>
              <%= link_to "削除", book_path(t.id), class:"btn-gradient-3d-red", method: :delete %>
              </h3>
            </div>
        </div>
</div>
<% end %>
<br>
<br>
<br>
<h3>ーユーザーがいいねした投稿一覧ー<h3>
<br>
    <% @user.liked_books.each do |t| %>
    <div class="blockwrapper">
        <div class=block>
          <p class= "blockthumb">
            <%= image_tag t.image, size: "100x350" if t.image? %>
          </p>
           <div class="bottomcontainer">           
              <a href="/users/<%= t.user.id %>">
              <%= t.user.name %></a>
              <%= t.created_at.to_s(:datetime_jp) %>
              <br>
             <%= link_to "詳細", book_path(t.id), class:"btn-gradient-3d-orange" %>
           </div>         
        </div>
    </div>
   <% end %>
</div>
<br>
<br>
<br>
<h3>
  <%= link_to "本一覧に戻る", books_path, class: "btn-flat-border" %>
</h3>
<br>
<br>
<br>
<br>
<br>